# Generated by Django 5.0.3 on 2024-03-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("authors", models.CharField(max_length=100)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
